# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dadedd32c46197c6ddbecea97e41a07574035d8aa3e70d24248bbc47839feb71d8f960cd9a56f26a3e8ff45c5c4bc0f7ca2a2c9ef5916261b8fb319bc7db0ebd

test:
  secret_key_base: 7a45e32abefe9f7ae440f2f5192216d080df374b66571f26fe25cc451d3e66a457a4772bb4f9b84d53f0dfb9860be20f58ee73c19ece0c860e07fa051e3487e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
